### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vincent-zurczak**
Add a new example showing how to use this plugin.
BTW, thanks for this plugin.

### CODE REVIEW

**Comment by frodefi** [comment]
I am glad you find it useful! And thank you for taking time to improve my little plugin :)

**Comment by frodefi** [comment]
I was perhaps a little quick. (And I still am a little quick, need to go in 3 minutes.) But I see you have a function to check if there is a minified version is not present. I already check for presence of minified files or not, with giving the two array properties names `minified` and `minifiedNotFound`. Does not those two cover what you are trying to achieve? If not, can you tell me what you are missing, and I can add a function or property to the plugin?

**Comment by vincent-zurczak** [comment]
Your **minifiedNotFound** array is useful if we want to match a specific file extension.
My function has a more global scope as it includes any extension. In the application I am working on, I have Boostrap in my Bower dependencies. And it comes with several files: js, css, svg, eot, woff... and I want to copy them too.

In fact, I want to copy minified JS/CSS if they exist.
And I also want to copy other Bower files that are neither JS, nor CSS.
Plus the JS and CSS files that do not have any minified version.

This function avoids specifying **all** the dependencies' extensions.  
And yes, this function also includes JS and CSS files. Since I have other file extensions, using _minifiedNotFound_ would just bring more code, so I did not add it. This is really another use case than the first one you showed. :)

BTW, I tried to use...

```
bowerMain( '*', 'min.*' )
```

... but it did not work to get any extension.
So, I finally came to the function solution.

**Comment by vincent-zurczak** [comment]
I have thought about it, and I understand what can be annoying with this function.
Basically, with a similar approach, we can get rid of your plugin. It does not result in smaller code, but it removes a plugin.

The thing is the plugin works very well when we just focus on CSS and JS.
However, when we want all the files, you have to know all the extensions in your dependencies.

Do you think the plugin could be upgraded to make the extension optional?
Have something like this in the result:
- **result.all**: all the files that match the extension (if any). It contains the minified and the not minified as an ordered array, just like main-bower-files.
- **result.minified**: all the minified files that match the extension (just like now).
- **result.notMinified**: all the files that match the extension and that do not have a minified version.

**result.all** is basically what we need to inject Bower dependencies in the right order in HTML files (**gulp-inject**). I think this would cover your base use case and mine without any extra code. I can prototype it if you want.

**Comment by frodefi** [comment]
Hi, Vincent!

A quick reply, I understand what you want. I will make so next week. Will
let you know and get your input when done.

Frode

**Comment by frodefi** [comment]
Had a crazy couple of weeks, hopefully will get time in a couple of days...

**Comment by vincent-zurczak** [comment]
Thanks for the notice. :)

**Comment by frodefi** [comment]
On Fri, May 22, 2015 at 5:53 PM, Vincent Zurczak notifications@github.com
wrote:

> _result.all_: all the files that match the extension (if any). It
> contains the minified and the not minified as an ordered array, just like
> main-bower-files.

So it contains both the minified and not minified version (+ other files
that exist only in one version)?

**Comment by vincent-zurczak** [comment]
No. It is an updated version of the original list.
Let's take an example, it will be more simple to explain.

If **bowerMain** returns **['module.js', 'module.service.js', 'module.directive.js']**, and that **module.service.js** and **module.directive.js** have a minified version, then _result.all_ will contain **['module.js', 'module.service.min.js', 'module.directive.min.js']**.

**result.all** is useful to inject scripts in the right order in HTML files (and using minified versions when available).
**result.notMinified** is useful to minify what was not already done.

**Comment by frodefi** [comment]
So in this case you would are not using the notMinified-list, right? Since
you are injecting the non-minified 'module.js' into the html.

**Comment by vincent-zurczak** [comment]
To only inject files in the HTML, I don't need the notMinified list.
It was just to highlight the result will contain several lists that cover different use cases.

result.all mixes minified and non-minified resources.
But it preserves the order given by bowerMain.

**Comment by frodefi** [comment]
Ok, I see

I have this suggestion, you can call the function several ways:

First of all, normally no need specify the second argument, the minified
name, it will just assume "min.extension" or "min.extension.gzip". Are
there other common ways of naming a minified file?

The file extension argument is also optional, when not given, then all
files are returned.
- bowerMain('js')
- bowerMain('js', 'mini.js') If the minified asset name has another form
  than standard
- bowerMain(['js','css'])
- bowerMain() All files

And the returned arrays are the ones that are as you suggest:
- all - all files, using the minified version if exists
- normal - all files, using only non-minified version if exist (nice for
  development)
- minified - all minified files
- minifiedNotFound all files that where a minified version is not found

What do you say?

**Comment by frodefi** [comment]
Note that I also added optional array for file extension:
- bowerMain(['js','css'])

**Comment by vincent-zurczak** [comment]
> First of all, normally no need specify the second argument, the minified name, it will just assume "min.extension" or "min.extension.gzip". Are there other common ways of naming a minified file?

Yes, I saw this. :)

> The file extension argument is also optional, when not given, then all files are returned.

I didn't see that. That's great then.
Because like I said, I have files that come with Twitter boostrap that are neither JS, nor CSS files.

> And the returned arrays are the ones that are as you suggest:

It looks very good.

**Comment by frodefi** [comment]
Great, I will make the adjustment within a few days (maybe today if I find
some time)

**Comment by vincent-zurczak** [comment]
Thanks! :+1:

**Pull request merged**
